name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
update-changelog: true  # This automatically updates CHANGELOG.md

template: |
  ## What's Changed

  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: 'No significant changes.'

exclude-labels:
  - 'skip-changelog'
